### PR TITLE
fixed blog figures

### PR DESCRIPTION
**Pull request by pauladkisson**
This PR should fix the figures in the blog, based on this [thread](https://stackoverflow.com/questions/40197197/how-can-i-display-an-image-in-a-post-on-a-blog-powered-by-jekyll/40198284#40198284).

But, it worked locally before this fix, so I'm not sure if there is a good way to test this before merging.

### CODE REVIEW

**Review by kabilar — APPROVED** [review]
Thank you.  Since we don't have previews available let's proceed and see if it works.

**Comment by kabilar** [comment]
Hi @pauladkisson, unfortunately the figures are still not displaying correctly.

**Comment by bendichter** [comment]
It did not work: https://www.dandiarchive.org/2024/09/09/data_reuse_000458.html

**Comment by bendichter** [comment]
@pauladkisson , when you say it worked before, what do you mean? Did you build the site with jekyll?

**Comment by pauladkisson** [comment]
> when you say it worked before, what do you mean? Did you build the site with jekyll?

Just rendering the markdown with VSCode.

**Comment by bendichter** [comment]
OK, yeah, that's not necessarily going to translate to the blog. Could you try rendering it with Jekyll?

**Comment by pauladkisson** [comment]
This tool https://jekyllrb.com/docs/
?

**Comment by bendichter** [comment]
Yeah, that's the one. That is what turns these markdown files into html

**Comment by kabilar** [comment]
You can try using the instructions in #63 for rendering it locally.  It might need some slight changes to get it working.

**Comment by pauladkisson** [comment]
I can build the site, but all the blog posts give this error (both on docker and on my machine directly): 
```
This site can’t be reached
http://0.0.7.230/03/08/microscopy-workshop.html is unreachable.
ERR_ADDRESS_UNREACHABLE
```

**Pull request merged**
