### PR TITLE
Add Sentry as in-kind supporter

### PR DESCRIPTION
**Pull request by kabilar**
## Description

- Sentry now provides [sponsorship](https://sentry.io/for/good/) to DANDI since we are an open-source project.

## Changes

- [x] Update footer
- [x] Test locally
  image

### CODE REVIEW

**Comment by yarikoptic** [comment]
Well, then not sure where we should stop listing services which we take benefit of as Open Source project: e.g. GitHub, codecov, RTD, Docker hub to name a few.  Sure there are degrees of how formal that sponsorship is across them, but still.
Is it requested by Sentry to list as part of the conditions?

**Comment by yarikoptic** [comment]
FWIW ATM we have it somewhat balanced "design wise"
image

**Comment by kabilar** [comment]
> Well, then not sure where we should stop listing services which we take benefit of as Open Source project: e.g. GitHub, codecov, RTD, Docker hub to name a few. Sure there are degrees of how formal that sponsorship is across them, but still. Is it requested by Sentry to list as part of the conditions?

Thanks @yarikoptic.  Thats a good point.  Sentry did not request that they be listed.  Perhaps there is a better way of acknowledging all of these supporters of our open source project.  I will brainstorm.  Closing this pull request for now.

**Comment by yarikoptic** [comment]
But indeed it would have been great to have some page acknowledging most if not all open/free services and projects we take "heavy" advantage of ! GitHub, terraform, Linux, Python, git, git-annex, django, vue, [vuetify-jsonschema-form](https://github.com/koumoul-dev/vuetify-jsonschema-form), ....  It would be useful even if only to show how great to have such a rich open/free  ecosystem.  Also would be hard to be exhaustive and/or draw a line where to stop though ;)

**Comment by kabilar** [comment]
> But indeed it would have been great to have some page acknowledging most if not all open/free services and projects we take "heavy" advantage of ! GitHub, terraform, Linux, Python, git, git-annex, django, vue, [vuetify-jsonschema-form](https://github.com/koumoul-dev/vuetify-jsonschema-form), .... It would be useful even if only to show how great to have such a rich open/free ecosystem. Also would be hard to be exhaustive and/or draw a line where to stop though ;)

I definitely agree.

**Pull request closed without merging**
