### PR TITLE
add events

### PR DESCRIPTION
**Pull request by bendichter**
I am not able to build jekyll locally, so I am trying this out

### CODE REVIEW

**Comment by satra** [comment]
do you want to do events separate from news? presently, i have simply done news + blog for such things.

**Comment by satra** [comment]
the showcase part didn't seem like an event, but more like feature stories.

**Comment by bendichter** [comment]
ah yes, I see the confusion. You want to create pages that highlight specific dandisets and call this a showcase.

I am trying to create something different. I want to organize a Gather Town poster session in September where we invite data submitters to present on their data. We need a website for information around this event: dates, links, registration, etc. I thought of calling this event "The DANDI Data Showcase", but if you'd rather use that name for blog posts about datasets that's fine, we can choose another name.

**Comment by satra** [comment]
> I want to organize a Gather Town poster session in September where we invite data submitters to present on their data.

if this is happening with allen, i would do that under a common umbrella. but for just announcing an event, i would just do a blog post.

**Pull request closed without merging**
